db:
  username: postgres
  password: postgres
  driver: PostgresDriver
  url: postgres:5444
  hosts: localhost,127.0.0.1
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 2

spring.profiles.active: qa
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update


logging:
  file:
    name: dmadev.log
    path: /
  level:
    root: info
    sql: warn
    com.dmadev.spring.database.pool.ConnectionPool: info

